In [6]:
'''
# Defining the input filepath
filepath = "GSE148375_processed_data.txt"

# Defining the output parquet filepath
parquet_path = "GSE148375_processed_data.parquet"

print("Reading into memory.")

# Reading the CSV file into a dataframe
df = pl.read_csv(filepath, separator='\t')
print("Saving as Parquet.")

# Writing the dataframe to a parquet file
df.write_parquet(parquet_path)
print("Done.")
'''

Reading into memory.
Saving as Parquet.
Done.

In [1]:
import sys
#!pip install XXX --target ./my_custom_packages
sys.path.append('./my_custom_packages')
#import dask.dataframe as dd
#import matplotlib.pyplot as plt
import polars as pl
import time
#import GEOparse
#pl.Config.set_tbl_rows(20)

In [3]:
# Printing the polars thread pool size
print(f"Polars Thread Pool: {pl.thread_pool_size()}")
# Checking the number of processing units
!nproc
# Getting the CPU architecture details
!lscpu | grep "CPU(s):"
# Displaying the available memory
!free -h

Polars Thread Pool: 112
112
CPU(s):                                  112
NUMA node0 CPU(s):                       0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110
NUMA node1 CPU(s):                       1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111
               total        used        free      shared  buff/cache   available
Mem:           503Gi        30Gi        21Gi       3.3Mi       445Gi       472Gi
Swap:          1.2Ti       1.2Gi       1.2Ti

In [3]:
'''
# Defining the text filepath
filepath = "~/Desktop/Stage-Ibrahima-main/GSE148375_processed_data.txt"
# Reading the CSV using dask
pcss_ddata = dd.read_csv(filepath, delimiter='\t')
# Displaying the first few rows
pcss_ddata.head()

# Dropping the ID_REF column
filtered_ddata = pcss_ddata.drop(columns=["ID_REF"])

# Melting the dataframe into a long format
melted_data = filtered_ddata.melt()

# Computing the unique values in the value column
uniques_dd = melted_data["value"].unique().compute()

# Printing the unique values as a list
print(list(uniques_dd))

'''

'filepath = "~/Desktop/Stage-Ibrahima-main/GSE148375_processed_data.txt"\npcss_ddata = dd.read_csv(filepath, delimiter=\'\t\')\npcss_ddata.head()\n\nfiltered_ddata = pcss_ddata.drop(columns=["ID_REF"])\n\nmelted_data = filtered_ddata.melt()\n\nuniques_dd = melted_data["value"].unique().compute()\n\nprint(list(uniques_dd))\n\n'

In [2]:
# Defining the parquet filepath
filepath = "GSE148375_processed_data.parquet"

# Reading the parquet file into a dataframe
pcss_pdata = pl.read_parquet(filepath)

# Displaying the first few rows
pcss_pdata.head()

shape: (5, 3_400)
┌────────────────────────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬────────┐
│ ID_REF                     ┆ 1900017 ┆ 1900029 ┆ 1900030 ┆ … ┆ 215771 ┆ 215772 ┆ 215773 ┆ 215827 │
│ ---                        ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str                        ┆ str     ┆ str     ┆ str     ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
╞════════════════════════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪════════╡
│ exm2268640-0_B_F_198484458 ┆ AG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ GG     │
│ 5                          ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆        │
│ exm41-0_B_F_1921435147     ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ GG     │
│ exm1916089-0_B_R_192768977 ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ GG     │
│ 5                          ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆        │
│ exm44-0_B_R_1921538602     ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ GG     │
│ exm46-0_T_F_1921333919     ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ GG     │
└────────────────────────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴────────┘

In [17]:
# Selecting all columns except ID_REF
#ft_data = pcss_pdata.select(pl.all().exclude("ID_REF"))

# Selecting unique values from the unpivoted data
#uniques_pl = unpivot_data.select(pl.col("value").unique())



# Dropping the ID_REF column
# ft_data_values_only =  pcss_pdata.drop("ID_REF")

# Getting unique values from the value column
# uniques_pl = ft_data_values_only.unpivot().get_column("value").unique()



# Starting the runtime timer
start1 = time.time()

# Selecting everything but the id column

# Initializing an empty list for unique values
uniques = []

# Looping through each column except the first
for col in pcss_pdata.columns[1:]:
    # Appending the unique values of the column
    uniques.append(pcss_pdata[col].unique())


# Concatenating and finding the overall unique values
uniques = pl.concat(uniques).unique()

# Printing the unique values as a list
print(uniques.to_list())



# Printing the total elapsed time
print(f"Took: {time.time() - start1:.2f}s")

['TT', 'GG', 'NC', 'GA', 'DI', 'TA', 'AG', 'ID', 'AT', 'II', 'CA', 'GC', 'DD', 'CG', 'CC', 'AC', 'AA']
Took: 6.86s

In [3]:
# Selecting all columns to check except ID_REF
columns_to_check = pl.all().exclude("ID_REF")

## Dropping II DD ID DI lines

# Starting the second runtime timer
start2 = time.time()

# Defining a list of mutations to remove
mutations_to_remove = ['DD', 'II', 'DI', 'ID']

# Checking which cells contain the mutations
cell_contains_true = columns_to_check.is_in(mutations_to_remove)

# Checking if any row contains the mutations horizontally
row_contains_true = pl.any_horizontal(cell_contains_true)

# Reversing the boolean to keep clean rows
rows_to_keep = ~row_contains_true

# Removing all similar lines
# Sorting by alphabetical value

# Finding the minimum value across the row
lowest_value = pl.min_horizontal(columns_to_check)

# Finding the maximum value across the row
highest_value = pl.max_horizontal(columns_to_check)

# Checking if the minimum and maximum values differ
difference_found = lowest_value != highest_value


# Filtering the dataframe to keep valid rows
clean_pcss_pdata = pcss_pdata.filter(difference_found & rows_to_keep)


# Printing the original row count
print(f"Number of rows original: {pcss_pdata.height}")
# Printing the cleaned row count
print(f"Number of rows in clean data: {clean_pcss_pdata.height} ")

# Printing the elapsed time
print(f"Took: {time.time() - start2:.2f}s")




# Changing NA and NC to the most frequent value of each row


# Starting the third runtime timer
start3 = time.time()

# Printing a check for any remaining NA or NC values
print(clean_pcss_pdata.select(pl.any_horizontal(pl.all().is_in(["NA", "NC"])).any()))


# Evaluating lists to extract valid data
valid_data = pl.concat_list(columns_to_check).list.eval(
    # Filtering out NA and NC values
    pl.element().filter(~pl.element().is_in(["NA", "NC"]))
)

# Adding the new valid_data column to the dataframe
clean_pcss_pdata = clean_pcss_pdata.with_columns(
    # Assigning the valid data
    valid_data = valid_data
)


# Calculating the mode for each row
row_mode = (
    # Selecting the valid data column
    pl.col("valid_data")
    # Counting the value frequencies
    .list.eval(pl.element().value_counts(sort=True))
    # Extracting the first element
    .list.first()
    # Getting the specific struct field
    .struct.field("")
)

# Adding the row_mode column to the dataframe
clean_pcss_pdata = clean_pcss_pdata.with_columns(
    # Assigning the calculated mode
    row_mode=row_mode
)


# Initializing an empty list for replacement rules
rules = []

# Looping through the columns to apply rules
for column in clean_pcss_pdata.columns[1:-2]:
    
    # Creating a conditional replacement rule
    rule = (
        # Checking if the cell is NA or NC
        pl.when(pl.col(column).is_in(["NA", "NC"]))
        # Replacing it with the row's mode
        .then(pl.col("row_mode"))
        # Keeping the original value otherwise
        .otherwise(pl.col(column))
        # Aliasing it back to the original column name
        .alias(column)
    )
    
    # Appending the rule to the list
    rules.append(rule)

# Applying all the generated rules to the dataframe
clean_pcss_pdata = clean_pcss_pdata.with_columns(rules)



# Dropping the temporary helper columns
clean_pcss_pdata = clean_pcss_pdata.drop(["valid_data", "row_mode"])

# Printing a final check to ensure NA and NC are gone
print(clean_pcss_pdata.select(pl.any_horizontal(pl.all().is_in(["NA", "NC"])).any()))

# Printing the elapsed time
print(f"Took: {time.time() - start3:.2f}s")

Number of rows original: 242901
Number of rows in clean data: 230965
Took: 2.20s
shape: (1, 1)
┌────────┐
│ ID_REF │
│ ---    │
│ bool   │
╞════════╡
│ true   │
└────────┘
shape: (1, 1)
┌────────┐
│ ID_REF │
│ ---    │
│ bool   │
╞════════╡
│ false  │
└────────┘
Took: 141.56s

In [8]:
# Starting the fourth runtime timer
start4 = time.time()

# Reading the human exome CSV file
humanexom_data = pl.read_csv("GPL18545_humanexome-12v1-1_a.csv", skip_rows = 7, schema_overrides = {"Chr": pl.String})

# Selecting only the ID and SNP columns
humanexom_data = humanexom_data.select(["IlmnID", "SNP"])

# Cleaning the SNP column characters
humanexom_data = humanexom_data.with_columns(
    # Replacing brackets and slashes with empty strings
    pl.col("SNP").str.replace_all(r"[\]\[/]", "")
)

# Renaming the ID column to match the other dataset
humanexom_data = humanexom_data.rename({"IlmnID": "ID_REF"})

# Displaying the head of the human exome data
#display(humanexom_data.head())

# Getting GEO data from the file
#annot_data = GEOparse.get_GEO(filepath = "GSE148375_series_matrix.txt")

# Initializing an empty dictionary for annotations
annot_data = {}

# Opening the matrix text file
with open("GSE148375_series_matrix.txt", "r") as f:
    # Initializing the line variable
    line = "X"
    # Looping while there are lines to read
    while line:
        # Reading the current line
        line = f.readline()
        # Checking if the line contains sample data
        if "!Sample_" in line:
            # Splitting the line by tabs
            content = line.strip().split("\t")
            
            # Extracting the key
            c = content[0]
            
            # Checking if the key already exists
            if c in annot_data.keys():
                # Initializing a counter
                i = 2
                # Appending an underscore to the key
                c += "_"
                # Looping to find a unique key name
                while c + str(i) in annot_data.keys():
                    # Incrementing the counter
                    i += 1
                # Appending the counter to the key
                c += str(i)

                # Storing the content in the dictionary
                annot_data[c] = content[1:]
            else:
                # Storing the content in the dictionary directly
                annot_data[c] = content[1:]
    


# Converting the dictionary into a polars dataframe
annot_data = pl.from_dict(annot_data)



# Formatting the extracted annotation columns
annot_data = annot_data.with_columns(
    # Parsing and casting the sample description
    Sample = pl.col("!Sample_description").str.replace_all(r'"', "").cast(pl.Int32),
    # Parsing and cleaning the sample status
    Status = pl.col("!Sample_characteristics_ch1_7").str.replace_all(r'"', "").str.split(":").list.get(1).str.strip_chars(),
    # Parsing and casting the sample age
    Age = pl.col("!Sample_characteristics_ch1_2").str.replace_all(r'"', "").str.split(":").list.get(1).str.strip_chars().cast(pl.Int8),
    # Parsing and cleaning the sample gender
    Gender = pl.col("!Sample_characteristics_ch1_3").str.replace_all(r'"', "").str.split(":").list.get(1).str.strip_chars()

)

# Selecting the final organized columns
annot_data = annot_data.select(["Sample", "Status", "Age", "Gender"])


# Displaying the head of the annotation dataframe
display(annot_data.head())



# Joining the cleaned data with the human exome data
merged_dataset = clean_pcss_pdata.join(humanexom_data, on = "ID_REF")
# Filtering out rows with specific specific SNP values
merged_dataset = merged_dataset.filter(~pl.col("SNP").is_in(["AT", "TA", "CG", "GC"]))

# Displaying the head of the merged dataset
#display(merged_dataset.head())

# Printing the elapsed time
print(f"Took: {time.time() - start4:.2f}s")

shape: (5, 4)
┌────────┬────────┬─────┬────────┐
│ Sample ┆ Status ┆ Age ┆ Gender │
│ ---    ┆ ---    ┆ --- ┆ ---    │
│ i32    ┆ str    ┆ i8  ┆ str    │
╞════════╪════════╪═════╪════════╡
│ 200026 ┆ Smoker ┆ 39  ┆ Male   │
│ 200027 ┆ Smoker ┆ 42  ┆ Male   │
│ 200028 ┆ Smoker ┆ 32  ┆ Female │
│ 200032 ┆ Smoker ┆ 33  ┆ Male   │
│ 200033 ┆ Smoker ┆ 48  ┆ Female │
└────────┴────────┴─────┴────────┘

shape: (5, 3_401)
┌───────────────────────────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬─────┐
│ ID_REF                        ┆ 1900017 ┆ 1900029 ┆ 1900030 ┆ … ┆ 215772 ┆ 215773 ┆ 215827 ┆ SNP │
│ ---                           ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ --- │
│ str                           ┆ str     ┆ str     ┆ str     ┆   ┆ str    ┆ str    ┆ str    ┆ str │
╞═══════════════════════════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪═════╡
│ exm-rs1000026-131_T_F_1990486 ┆ GG      ┆ AA      ┆ GG      ┆ … ┆ GG     ┆ AG     ┆ AG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000053-131_T_F_1990486 ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000110-131_T_F_1990486 ┆ GG      ┆ AG      ┆ AG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000113-131_B_F_1990477 ┆ GG      ┆ AG      ┆ GG      ┆ … ┆ AG     ┆ AA     ┆ GG     ┆ TC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000158-131_T_F_1990486 ┆ AG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
└───────────────────────────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴─────┘

Took: 1.49s

In [9]:
# Starting the fifth runtime timer
start5 = time.time()


# Creating a dataset of 0, 1, and 2


# Mapping nucleotide flips
flip = {"A": "T", "T": "A", "C": "G", "G": "C"}

# Initializing an empty rules list
rules = []


# Extracting the reference allele
ref = pl.col("SNP").str.slice(0, 1)
# Extracting the alternate allele
alt = pl.col("SNP").str.slice(1, 1)

# Replacing the reference with its flip
flip_ref = ref.replace(flip)
# Replacing the alternate with its flip
flip_alt = alt.replace(flip)


# Looping through each column to apply calculations
for c in clean_pcss_pdata.columns[1:-1]:

    # Extracting the first allele of the column
    allele1 = pl.col(c).str.slice(0, 1)
    # Extracting the second allele of the column
    allele2 = pl.col(c).str.slice(1, 1)

    # Checking for forward matches
    forward = ((allele1 == ref) | (allele1 == alt)) & ((allele2 == ref) | (allele2 == alt))
    # Checking for backward matches
    backward = ((allele1 == flip_ref) | (allele1 == flip_alt)) & ((allele2 == flip_ref) | (allele2 == flip_alt))
    
    
    # Building the logic rule
    rule = (pl
    # Evaluating the forward condition
    .when(forward)
    # Calculating the forward cost
    .then((allele1 != ref).cast(pl.Int8) + (allele2 != ref).cast(pl.Int8))
    # Evaluating the backward condition
    .when(backward)
    # Calculating the backward cost
    .then((allele1 != flip_ref).cast(pl.Int8) + (allele2 != flip_ref).cast(pl.Int8))
    # Assigning None if conditions fail
    .otherwise(None)
    # Aliasing the column name
    .alias(c))
    
    # Appending the rule to the list
    rules.append(rule)
    
    

# Creating the final cost matrix using the rules
cost_matrix = merged_dataset.select(rules)

# Printing the elapsed time
print(f"Took: {time.time() - start5:.2f}s")

Took: 11.57s

In [11]:
# Displaying the head of the cost matrix
display(cost_matrix.head(10))
# Displaying the head of the merged dataset
display(merged_dataset.head(10))
# Displaying the head of the annotation data
display(annot_data.head(10))

'''
# Printing a status message
print("Saving datasets")

# Writing the cost matrix to parquet
cost_matrix.write_parquet("cost_matrix_processed.parquet")
# Writing the merged dataset to parquet
merged_dataset.write_parquet("merged_dataset_processed.parquet")
# Writing the annotation data to parquet
annot_data.write_parquet("annot_data_processed.parquet")

print("Done.")
'''

shape: (10, 3_398)
┌─────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬────────┐
│ 1900017 ┆ 1900029 ┆ 1900030 ┆ 1900031 ┆ … ┆ 215769 ┆ 215771 ┆ 215772 ┆ 215773 │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i8      ┆ i8      ┆ i8      ┆ i8      ┆   ┆ i8     ┆ i8     ┆ i8     ┆ i8     │
╞═════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪════════╡
│ 2       ┆ 0       ┆ 2       ┆ 1       ┆ … ┆ 2      ┆ 0      ┆ 2      ┆ 1      │
│ 2       ┆ 2       ┆ 2       ┆ 2       ┆ … ┆ 1      ┆ 2      ┆ 2      ┆ 2      │
│ 2       ┆ 1       ┆ 1       ┆ 2       ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 2      │
│ 2       ┆ 1       ┆ 2       ┆ 2       ┆ … ┆ 2      ┆ 0      ┆ 1      ┆ 0      │
│ 1       ┆ 2       ┆ 2       ┆ 2       ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 2      │
│ 1       ┆ 1       ┆ 2       ┆ 1       ┆ … ┆ 0      ┆ 1      ┆ 2      ┆ 2      │
│ 0       ┆ 0       ┆ 0       ┆ 0       ┆ … ┆ 0      ┆ 0      ┆ 0      ┆ 0      │
│ 0       ┆ 1       ┆ 1       ┆ 0       ┆ … ┆ 0      ┆ 0      ┆ 0      ┆ 0      │
│ 1       ┆ 2       ┆ 2       ┆ 2       ┆ … ┆ 0      ┆ 1      ┆ 2      ┆ 1      │
│ 2       ┆ 2       ┆ 2       ┆ 1       ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 2      │
└─────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴────────┘

shape: (10, 3_401)
┌───────────────────────────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬─────┐
│ ID_REF                        ┆ 1900017 ┆ 1900029 ┆ 1900030 ┆ … ┆ 215772 ┆ 215773 ┆ 215827 ┆ SNP │
│ ---                           ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ --- │
│ str                           ┆ str     ┆ str     ┆ str     ┆   ┆ str    ┆ str    ┆ str    ┆ str │
╞═══════════════════════════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪═════╡
│ exm-rs1000026-131_T_F_1990486 ┆ GG      ┆ AA      ┆ GG      ┆ … ┆ GG     ┆ AG     ┆ AG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000053-131_T_F_1990486 ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000110-131_T_F_1990486 ┆ GG      ┆ AG      ┆ AG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000113-131_B_F_1990477 ┆ GG      ┆ AG      ┆ GG      ┆ … ┆ AG     ┆ AA     ┆ GG     ┆ TC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000158-131_T_F_1990486 ┆ AG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000192-131_B_F_1990477 ┆ AG      ┆ AG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ TC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000203-131_T_R_1990486 ┆ AA      ┆ AA      ┆ AA      ┆ … ┆ AA     ┆ AA     ┆ AA     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs10005603-131_T_R_199048 ┆ AA      ┆ CA      ┆ CA      ┆ … ┆ AA     ┆ AA     ┆ AA     ┆ AC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000797-131_T_R_1990486 ┆ AG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ AG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1001021-131_B_F_1990477 ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ AG     ┆ TC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
└───────────────────────────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴─────┘

shape: (10, 4)
┌────────┬────────────┬─────┬────────┐
│ Sample ┆ Status     ┆ Age ┆ Gender │
│ ---    ┆ ---        ┆ --- ┆ ---    │
│ i32    ┆ str        ┆ i8  ┆ str    │
╞════════╪════════════╪═════╪════════╡
│ 200026 ┆ Smoker     ┆ 39  ┆ Male   │
│ 200027 ┆ Smoker     ┆ 42  ┆ Male   │
│ 200028 ┆ Smoker     ┆ 32  ┆ Female │
│ 200032 ┆ Smoker     ┆ 33  ┆ Male   │
│ 200033 ┆ Smoker     ┆ 48  ┆ Female │
│ 200034 ┆ Smoker     ┆ 33  ┆ Male   │
│ 200146 ┆ Smoker     ┆ 29  ┆ Female │
│ 200218 ┆ Non-smoker ┆ 46  ┆ Female │
│ 200264 ┆ Smoker     ┆ 46  ┆ Female │
│ 200266 ┆ Smoker     ┆ 53  ┆ Female │
└────────┴────────────┴─────┴────────┘

Saving datasets
Done.