In [2]:
import sys
#!pip install XXX --target ./my_custom_packages
sys.path.append('./my_custom_packages')
import polars as pl
import time
#pl.Config.set_tbl_rows(20)

In [3]:
humanexom_data = pl.read_csv("GPL18545_humanexome-12v1-1_a.csv", skip_rows = 7, schema_overrides = {"Chr": pl.String})
display(humanexom_data.columns)
display(humanexom_data.head())

merged_dataset = pl.read_parquet("merged_dataset_processed.parquet")
display(merged_dataset.head())

cost_matrix = pl.read_parquet("cost_matrix_processed.parquet")
display(cost_matrix.head())


# #CHROM, POS, ID, REF, ALT, QUAL, FILTER, INFO, FORMAT

['IlmnID',
 'Name',
 'IlmnStrand',
 'SNP',
 'AddressA_ID',
 'AlleleA_ProbeSeq',
 'AddressB_ID',
 'AlleleB_ProbeSeq',
 'GenomeBuild',
 'Chr',
 'MapInfo',
 'Ploidy',
 'Species',
 'Source',
 'SourceVersion',
 'SourceStrand',
 'SourceSeq',
 'TopGenomicSeq',
 'BeadSetID',
 'Exp_Clusters',
 'RefStrand']

shape: (5, 21)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ IlmnID     ┆ Name       ┆ IlmnStrand ┆ SNP   ┆ … ┆ TopGenomi ┆ BeadSetID ┆ Exp_Clust ┆ RefStrand │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ cSeq      ┆ ---       ┆ ers       ┆ ---       │
│ str        ┆ str        ┆ str        ┆ str   ┆   ┆ ---       ┆ i64       ┆ ---       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆ str       ┆           ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ exm-IND1-2 ┆ exm-IND1-2 ┆ MINUS      ┆ [D/I] ┆ … ┆ GAGGGCCGC ┆ 662       ┆ 3         ┆ -         │
│ 00449980-0 ┆ 00449980   ┆            ┆       ┆   ┆ TCAGCGAGG ┆           ┆           ┆           │
│ _M_R_19904 ┆            ┆            ┆       ┆   ┆ GCGGGACAG ┆           ┆           ┆           │
│ …          ┆            ┆            ┆       ┆   ┆ AAC…      ┆           ┆           ┆           │
│ exm-IND1-2 ┆ exm-IND1-2 ┆ MINUS      ┆ [D/I] ┆ … ┆ CATGGAGCT ┆ 662       ┆ 3         ┆ -         │
│ 01453487-0 ┆ 01453487   ┆            ┆       ┆   ┆ GTGTTTGTA ┆           ┆           ┆           │
│ _M_R_19904 ┆            ┆            ┆       ┆   ┆ CCCCACCTC ┆           ┆           ┆           │
│ …          ┆            ┆            ┆       ┆   ┆ CAA…      ┆           ┆           ┆           │
│ exm-IND1-8 ┆ exm-IND1-8 ┆ PLUS       ┆ [I/D] ┆ … ┆ CTTTATGCA ┆ 688       ┆ 3         ┆ +         │
│ 5310248-0_ ┆ 5310248    ┆            ┆       ┆   ┆ GCCCAAGTC ┆           ┆           ┆           │
│ P_F_199048 ┆            ┆            ┆       ┆   ┆ AGAACCATG ┆           ┆           ┆           │
│ …          ┆            ┆            ┆       ┆   ┆ GCT…      ┆           ┆           ┆           │
│ exm-IND10- ┆ exm-IND10- ┆ PLUS       ┆ [I/D] ┆ … ┆ GGGAACACC ┆ 662       ┆ 3         ┆ +         │
│ 102817747- ┆ 102817747  ┆            ┆       ┆   ┆ TGGCTCTGC ┆           ┆           ┆           │
│ 0_P_F_1990 ┆            ┆            ┆       ┆   ┆ AAGTTTTGT ┆           ┆           ┆           │
│ …          ┆            ┆            ┆       ┆   ┆ GCC…      ┆           ┆           ┆           │
│ exm-IND10- ┆ exm-IND10- ┆ MINUS      ┆ [D/I] ┆ … ┆ CTGTGTTTA ┆ 662       ┆ 3         ┆ -         │
│ 18329639-0 ┆ 18329639   ┆            ┆       ┆   ┆ TTTGGTTCC ┆           ┆           ┆           │
│ _M_R_19904 ┆            ┆            ┆       ┆   ┆ TTAGGTAAA ┆           ┆           ┆           │
│ …          ┆            ┆            ┆       ┆   ┆ GCC…      ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 3_401)
┌───────────────────────────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬─────┐
│ ID_REF                        ┆ 1900017 ┆ 1900029 ┆ 1900030 ┆ … ┆ 215772 ┆ 215773 ┆ 215827 ┆ SNP │
│ ---                           ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ --- │
│ str                           ┆ str     ┆ str     ┆ str     ┆   ┆ str    ┆ str    ┆ str    ┆ str │
╞═══════════════════════════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪═════╡
│ exm-rs1000026-131_T_F_1990486 ┆ GG      ┆ AA      ┆ GG      ┆ … ┆ GG     ┆ AG     ┆ AG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000053-131_T_F_1990486 ┆ GG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000110-131_T_F_1990486 ┆ GG      ┆ AG      ┆ AG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000113-131_B_F_1990477 ┆ GG      ┆ AG      ┆ GG      ┆ … ┆ AG     ┆ AA     ┆ GG     ┆ TC  │
│ 6…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
│ exm-rs1000158-131_T_F_1990486 ┆ AG      ┆ GG      ┆ GG      ┆ … ┆ GG     ┆ GG     ┆ GG     ┆ AG  │
│ 7…                            ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆     │
└───────────────────────────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴─────┘

shape: (5, 3_398)
┌─────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬────────┐
│ 1900017 ┆ 1900029 ┆ 1900030 ┆ 1900031 ┆ … ┆ 215769 ┆ 215771 ┆ 215772 ┆ 215773 │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i8      ┆ i8      ┆ i8      ┆ i8      ┆   ┆ i8     ┆ i8     ┆ i8     ┆ i8     │
╞═════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪════════╡
│ 2       ┆ 0       ┆ 2       ┆ 1       ┆ … ┆ 2      ┆ 0      ┆ 2      ┆ 1      │
│ 2       ┆ 2       ┆ 2       ┆ 2       ┆ … ┆ 1      ┆ 2      ┆ 2      ┆ 2      │
│ 2       ┆ 1       ┆ 1       ┆ 2       ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 2      │
│ 2       ┆ 1       ┆ 2       ┆ 2       ┆ … ┆ 2      ┆ 0      ┆ 1      ┆ 0      │
│ 1       ┆ 2       ┆ 2       ┆ 2       ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 2      │
└─────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴────────┘

In [4]:
cost_matrix = cost_matrix.with_columns(
    merged_dataset.select(merged_dataset.columns[0]).rename({"ID_REF": "IlmnID"})
)

cost_matrix = cost_matrix.with_columns(pl.all().cast(pl.String))


gmap = {
    0: "0/0",
    1: "0/1",
    2: "1/1",
    None: "./."
}

cost_matrix = cost_matrix.with_columns(
    pl.col(c).replace(gmap) for c in cost_matrix.columns
)

display(cost_matrix.head())


humanexom_data = humanexom_data.rename({"Name": "ID", "MapInfo": "POS", "Chr": "#CHROM"})

humanexom_data = humanexom_data.with_columns(
    pl.lit(".").alias("QUAL"),
    pl.lit("PASS").alias("FILTER"),
    pl.lit(".").alias("INFO"),
    pl.lit("GT").alias("FORMAT"),
    pl.col("SNP").str.replace_all(r"[\]\[/]", "")
)
humanexom_data = humanexom_data.with_columns(
    pl.col("SNP").str.slice(0, 1).alias("REF"),
    pl.col("SNP").str.slice(1, 1).alias("ALT")

)

humanexom_data = humanexom_data.select(["#CHROM", "POS", "ID", "REF", "ALT", "QUAL", "FILTER", "INFO", "FORMAT", "IlmnID"])

vcf = humanexom_data.join(cost_matrix, on = "IlmnID")

vcf = vcf.select(pl.all().exclude("IlmnID"))



display(vcf.head())

shape: (5, 3_399)
┌─────────┬─────────┬─────────┬─────────┬───┬────────┬────────┬────────┬───────────────────────────┐
│ 1900017 ┆ 1900029 ┆ 1900030 ┆ 1900031 ┆ … ┆ 215771 ┆ 215772 ┆ 215773 ┆ IlmnID                    │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---                       │
│ str     ┆ str     ┆ str     ┆ str     ┆   ┆ str    ┆ str    ┆ str    ┆ str                       │
╞═════════╪═════════╪═════════╪═════════╪═══╪════════╪════════╪════════╪═══════════════════════════╡
│ 1/1     ┆ 0/0     ┆ 1/1     ┆ 0/1     ┆ … ┆ 0/0    ┆ 1/1    ┆ 0/1    ┆ exm-rs1000026-131_T_F_199 │
│         ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆ 04867…                    │
│ 1/1     ┆ 1/1     ┆ 1/1     ┆ 1/1     ┆ … ┆ 1/1    ┆ 1/1    ┆ 1/1    ┆ exm-rs1000053-131_T_F_199 │
│         ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆ 04867…                    │
│ 1/1     ┆ 0/1     ┆ 0/1     ┆ 1/1     ┆ … ┆ 1/1    ┆ 1/1    ┆ 1/1    ┆ exm-rs1000110-131_T_F_199 │
│         ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆ 04867…                    │
│ 1/1     ┆ 0/1     ┆ 1/1     ┆ 1/1     ┆ … ┆ 0/0    ┆ 0/1    ┆ 0/0    ┆ exm-rs1000113-131_B_F_199 │
│         ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆ 04776…                    │
│ 0/1     ┆ 1/1     ┆ 1/1     ┆ 1/1     ┆ … ┆ 1/1    ┆ 1/1    ┆ 1/1    ┆ exm-rs1000158-131_T_F_199 │
│         ┆         ┆         ┆         ┆   ┆        ┆        ┆        ┆ 04867…                    │
└─────────┴─────────┴─────────┴─────────┴───┴────────┴────────┴────────┴───────────────────────────┘

shape: (5, 3_407)
┌────────┬───────────┬───────────────┬─────┬───┬────────┬────────┬────────┬────────┐
│ #CHROM ┆ POS       ┆ ID            ┆ REF ┆ … ┆ 215769 ┆ 215771 ┆ 215772 ┆ 215773 │
│ ---    ┆ ---       ┆ ---           ┆ --- ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ i64       ┆ str           ┆ str ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
╞════════╪═══════════╪═══════════════╪═════╪═══╪════════╪════════╪════════╪════════╡
│ 21     ┆ 38934599  ┆ exm-rs1000026 ┆ A   ┆ … ┆ 1/1    ┆ 0/0    ┆ 1/1    ┆ 0/1    │
│ 2      ┆ 12790328  ┆ exm-rs1000053 ┆ A   ┆ … ┆ 0/1    ┆ 1/1    ┆ 1/1    ┆ 1/1    │
│ 9      ┆ 117908721 ┆ exm-rs1000110 ┆ A   ┆ … ┆ 1/1    ┆ 1/1    ┆ 1/1    ┆ 1/1    │
│ 5      ┆ 150240076 ┆ exm-rs1000113 ┆ T   ┆ … ┆ 1/1    ┆ 0/0    ┆ 0/1    ┆ 0/0    │
│ 20     ┆ 36599904  ┆ exm-rs1000158 ┆ A   ┆ … ┆ 1/1    ┆ 1/1    ┆ 1/1    ┆ 1/1    │
└────────┴───────────┴───────────────┴─────┴───┴────────┴────────┴────────┴────────┘

In [5]:
filename = "axome_counts.vcf"

with open(filename, "w") as f:
    f.write("##fileformat=VCFv4.2\n")

with open(filename, "a") as f:
    vcf.write_csv(f, separator = "\t")

In [6]:
%%bash

echo "--- SYSTEM INFO ---"
uname -a
echo "--- FILE INFO ---"
file ./plink2

--- SYSTEM INFO ---
Linux lambcomp02.ccbb.utexas.edu 6.8.0-117-generic #117-Ubuntu SMP PREEMPT_DYNAMIC Tue May  5 19:26:24 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux
--- FILE INFO ---
./plink2: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=76da560d9bc466fc2e791431251025721168d89b, for GNU/Linux 3.2.0, with debug_info, not stripped

In [7]:
%%bash

#Give the file permission to run
chmod +x plink2

echo "Sorting data"

./plink2 \
--vcf axome_counts.vcf \
--autosome \
--sort-vars \
--make-pgen \
--out axome_counts_plink_data_sorted


# SORT-VARS: sorts the genome in chromosone order
# MAKE-PGEN: saves the file in compressed plink file

echo "Filtering data"
./plink2 \
--pfile axome_counts_plink_data_sorted \
--geno 0.05 \
--mind 0.05 \
--maf 0.01 \
--make-bed \
--out plink_data

# AUTOSOME: Drop the gender chromosone 23 to account for it you can let it guess using impute-sex
# however ml could learning to predict male vs female instead of smoking status
# GENO: Filter when SNP is missing in more than 5% of patients
# MIND: Filters when a genotype is missing more than 5% of SNPs
# MAF: Filters for variant in less than 1% of patients
# MAKE-BED: Converts the data in PLINK's binary format for efficiency

Sorting data
PLINK v2.0.0-a.7.1LM AVX2 Intel (4 May 2026)        cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to axome_counts_plink_data_sorted.log.
Options in effect:
  --autosome
  --make-pgen
  --out axome_counts_plink_data_sorted
  --sort-vars
  --vcf axome_counts.vcf

Start time: Thu Jun 18 19:25:01 2026
515459 MiB RAM detected, ~226626 available; reserving 226562 MiB for main
workspace.
Using up to 112 threads (change this with --threads).
--vcf: 203416 variants scanned; 4558 excluded by --autosome, 198858 remaining.ariants scanned. scanned.cf: 46k variants scanned.nts scanned.
--vcf: axome_counts_plink_data_sorted-temporary.pgen +
axome_counts_plink_data_sorted-temporary.pvar.zst +
axome_counts_plink_data_sorted-temporary.psam written.
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) loaded from
axome_counts_plink_data_sorted-temporary.psam.
198858 variants loaded from axome_counts_plink_data_sorted-temporary.pvar.zst.
Note: No phenotype data present.
Writing axome_counts_plink_data_sorted.pvar ... done.
Writing axome_counts_plink_data_sorted.psam ... done.
Writing axome_counts_plink_data_sorted.pgen ... 326598done.
End time: Thu Jun 18 19:25:04 2026
Filtering data
PLINK v2.0.0-a.7.1LM AVX2 Intel (4 May 2026)        cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to plink_data.log.
Options in effect:
  --geno 0.05
  --maf 0.01
  --make-bed
  --mind 0.05
  --out plink_data
  --pfile axome_counts_plink_data_sorted

Start time: Thu Jun 18 19:25:04 2026
515459 MiB RAM detected, ~226962 available; reserving 226898 MiB for main
workspace.
Using up to 112 threads (change this with --threads).
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) loaded from
axome_counts_plink_data_sorted.psam.
198858 variants loaded from axome_counts_plink_data_sorted.pvar.
Note: No phenotype data present.
Calculating sample missingness rates... 326598done.
0 samples removed due to missing genotype data (--mind).
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) remaining
after main filters.
Calculating allele frequencies... 326598done.
--geno: 0 variants removed due to missing genotype data.
153649 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
45209 variants remaining after main filters.
Writing plink_data.fam ... done.
Writing plink_data.bim ... done.
Writing plink_data.bed ... 326999done.
End time: Thu Jun 18 19:25:04 2026

In [77]:
%%bash


./plink2 \
--bfile plink_data \
--indep-pairwise 50 5 0.2 \
--out ld_pruning_plink_data

# INDEP-PAIRWISE: 50 SNP window, shift by 5 at a time, and drop when correlated >0.2 with another snp in that window
# OUT: List of remaining snps

PLINK v2.0.0-a.7.1LM AVX2 Intel (4 May 2026)        cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to ld_pruning_plink_data.log.
Options in effect:
  --bfile plink_data
  --indep-pairwise 50 5 0.2
  --out ld_pruning_plink_data

Start time: Wed Jun 17 20:52:35 2026
515459 MiB RAM detected, ~480505 available; reserving 257729 MiB for main
workspace.
Allocated 193296 MiB successfully, after larger attempt(s) failed.
Using up to 112 threads (change this with --threads).
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) loaded from
plink_data.fam.
45209 variants loaded from plink_data.bim.
Note: No phenotype data present.
Calculating allele frequencies... done.
--indep-pairwise (11 compute threads): 5010919/45209 variants removed.
Variant lists written to ld_pruning_plink_data.prune.in and
ld_pruning_plink_data.prune.out .
End time: Wed Jun 17 20:52:35 2026

In [9]:
%%bash

./plink2 \
--bfile plink_data \
--extract ld_pruning_plink_data.prune.in \
--pca 10 \
--out ancestry_pca_plink_data

# To control for genetic background

PLINK v2.0.0-a.7.1LM AVX2 Intel (4 May 2026)        cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to ancestry_pca_plink_data.log.
Options in effect:
  --bfile plink_data
  --out ancestry_pca_plink_data
  --pca 10

Start time: Thu Jun 18 19:25:34 2026
515459 MiB RAM detected, ~226187 available; reserving 226123 MiB for main
workspace.
Using up to 112 threads (change this with --threads).
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) loaded from
plink_data.fam.
45209 variants loaded from plink_data.bim.
Note: No phenotype data present.
Calculating allele frequencies... done.
Constructing GRM: 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to ancestry_pca_plink_data.eigenvec , and
eigenvalues written to ancestry_pca_plink_data.eigenval .
End time: Thu Jun 18 19:25:36 2026

In [10]:
%%bash

./plink2 \
--bfile plink_data \
--recode A \
--out matrix_plink_data

# CSV file with SNPs

PLINK v2.0.0-a.7.1LM AVX2 Intel (4 May 2026)        cog-genomics.org/plink/2.0/
(C) 2005-2026 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to matrix_plink_data.log.
Options in effect:
  --bfile plink_data
  --export A
  --out matrix_plink_data

Start time: Thu Jun 18 19:25:58 2026
515459 MiB RAM detected, ~230368 available; reserving 230304 MiB for main
workspace.
Using up to 112 threads (change this with --threads).
3398 samples (0 females, 0 males, 3398 ambiguous; 3398 founders) loaded from
plink_data.fam.
45209 variants loaded from plink_data.bim.
Note: No phenotype data present.
--export A pass 1/1: loading... 0writing... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
--export A: matrix_plink_data.raw written.
End time: Thu Jun 18 19:25:59 2026